# UNIT TYPE
PATH_UNIT = "Path Unit"
SOCKET_UNIT = "Socket Unit"
TIMER_UNIT = "Timer Unit"
SWAP_UNIT = "Swap Unit"
TARGET_UNIT = "Target Unit"
ENABLE_UNIT = "Service enable"
DISABLE_UNIT = "Service disable"

# VERIFY_TYPE
VERIFY_PATH_TYPE = [PATH_UNIT, TIMER_UNIT]
VERIFY_LOG_TYPE = [SOCKET_UNIT, SWAP_UNIT, ENABLE_UNIT, DISABLE_UNIT]
START_MODEL_TYPE = [PATH_UNIT, SOCKET_UNIT, TIMER_UNIT, SWAP_UNIT, TARGET_UNIT]
REBOOT_MODEL_TYPE = [ENABLE_UNIT, DISABLE_UNIT]

# CONFIG FILE KEY
K_TEST = "test"
k_VERIFY = "verify"

# CHECK RESULT
CHECK_RESULT = "Check result"
PASS = "PASS"
FAIL = "FAIL"

# VERIFY_MODEL_TYPE
MODEL_START = "start"
MODEL_REBOOT = "reboot"
